export enum HOME_ENUM {
  TOP_ELEMENT = 'TOP_ELEMENT',
  GOOGLE_LOGO = 'GOOGLE_LOGO',
  SEARCH_BAR = 'SEARCH_BAR',
  ICON_BUTTONS = 'ICON_BUTTONS',
  INFO_CARDS = 'INFO_CARDS',
  NEWS_CARDS = 'NEWS_CARDS',
}
