const colors = {
  defaultPrimary: '#1e1e1e',
  defaultSecondary: '#2a2a2a',
  defaultTertiary: '#121212',
  flaskBlue: '#A3B2FF',
  green: '#34A853',
  white: '#FFFFFF',
  icon_primary: '#cfcfcf',
  yellowishBrown: '#5c4b23',
  yellow: '#fdd835',
  darkNavy: '#2c2f3c',
  lightBlue: '#aabfff',
  greenish: '#2a3b2c',
  lightGreen: '#c3fcd4',
  reddish: '#3a1f1f',
  lightRed: '#ffaaaa',
  black: '#000000',
  yellowish: '#fff200',
  borderColor: '#333',
  lightGray: '#ccc',
  gray: '#aaa',
  darkGray: '#333',
  lightGrayText: '#ccc',
  darkBackground: '#121212',
  blackBackground: '#000',
  whiteBackground: '#fff',
  selectedButtonBackground: '#3a3a3c',
  selectedButtonText: '#a0b4ff',
  voiceRecognitionColors: ['#4285F4', '#EA4335', '#FBBC05', '#34A853'],
  buttonBorderColor: '#888',
  buttonTextColor: '#fff',
  transcriptTextColor: '#eee',
  speakNowTextColor: '#fff',
  searchCon: '#1c1c1e',
};

export default colors;
